# Generated by Django 4.2.16 on 2024-11-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='snippets_images/'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
