# Generated by Django 4.2.16 on 2024-11-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_imagen_snippet_precio_snippet_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
